### ISSUE TITLE
DSS Auth: Fine Level Access Control (FLAC)

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/data-store#74]
- [x] decide on style for  FLAC: RelationalDB or DynamoDB (going with **DynamoDB**)
- [x] decide on FQID vs UUID for primary key (leaning toward UUID only - see discussion in #93)
- [x] terraform out necessary infra (see https://github.com/DataBiosphere/data-store-auth/issues/10 and https://github.com/DataBiosphere/data-store/pull/131/files)
- [x] need DynamoDB to tie into AuthZ service (see #141 for Flac mixin for Auth0 authorize class, )
- [x] need something to manage users (document? tools? depends on how AuthZ is implemented) (see #144 for implementation of dss-ops functionality to update the FLAC table in dynamodb)

**Comment by amarjandu** [comment]
Related Spike ticket: https://github.com/DataBiosphere/data-store/issues/53

Specifically, this comment: https://github.com/DataBiosphere/data-store/issues/53#issuecomment-582476926

**Comment by chmreid** [comment]
Related user stories and MVP: #93

**Comment by chmreid** [comment]
This will be closed when #141, #144, and #150 (three-part chain of PRs) are merged into master.

**Comment by chmreid** [comment]
Done! 🎉 🌮 🎉
